apiVersion: v1
kind: Service
metadata:
  name: static-data-app2-service
  labels:
    name: static-data-app2-service
    app: static-data-app2   
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    name: static-data-app2-pod
    app: static-data-app2