apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-data-app2-deployment
  labels:
    app: static-data-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      name: static-data-app2-pod
      app: static-data-app2
  template:
    metadata: 
      name: static-data-app2-pod
      labels:
        name: static-data-app2-pod
        app: static-data-app2
    spec:
      containers:
      - name: static-data-app2
        image: bashkimkasa/static-data-app2
        ports:
        - containerPort: 8082